######################################################################
# Automatically generated by qmake (3.0) ?? 9? 29 13:47:23 2016
######################################################################

QT+= widgets
TEMPLATE = app
TARGET = 02test
INCLUDEPATH += .

# Input
HEADERS += widget.h
FORMS += widget.ui
SOURCES += main.cpp widget.cpp
